# Generated by Django 5.1.2 on 2024-10-21 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('image', models.ImageField(null=True, upload_to='imagenes', verbose_name='imagen')),
                ('upload', models.FileField(upload_to='archivos_pdf')),
                ('description', models.TextField(null=True, verbose_name='descripcion')),
            ],
        ),
    ]
